spring:
  cloud:
    config:
      server:
        git:
          password: your password
          searchPaths: config-files
          uri: https://github.com/shuimuconcept/zlgspringcloud
          username: your username
      label: master
  application:
    name: config-server
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/